import { chromium } from "playwright"
const G = "C:/Users/tetsu/AppData/Local/Temp/claude/c--Users-tetsu-OneDrive-Desktop-EDSP-practice-shiftb-master/c220253c-6246-4aa2-88c5-4460cc464d09/scratchpad/guide"
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 402, height: 870 }, deviceScaleFactor: 2 })
await page.goto("http://localhost:3100/dev/guide-demo/demo?step=8", { waitUntil: "domcontentloaded", timeout: 240000 })
await page.waitForSelector("[data-guide-overlay]", { state: "attached", timeout: 180000 })
await page.addStyleTag({ content: "nextjs-portal{display:none!important}" })
await page.waitForTimeout(2600)
await page.screenshot({ path: `${G}/shots/impl/v_08.png` })
await page.evaluate("window.__guideStep(5)")
await page.waitForTimeout(1500)
await page.screenshot({ path: `${G}/shots/impl/v_05.png` })
await page.evaluate("window.__guideStep(14)")
await page.waitForTimeout(1500)
await page.screenshot({ path: `${G}/shots/impl/v_14_ring.png` })
await page.waitForTimeout(2400)
await page.screenshot({ path: `${G}/shots/impl/v_14_card.png` })
await page.evaluate("window.__guideStep(17)")
await page.waitForTimeout(2600)
await page.screenshot({ path: `${G}/shots/impl/v_17.png` })
await browser.close()
console.log("verify captured")
