// 自動生成: scripts/gen_share_arco.tsx (編集禁止・再生成で更新)
// シェアOG画像に埋め込む ArcoChan SVG (kind別ポーズ)。
import type { ShareKind } from "@/app/_libs/shareCard"

export const ARCO_SVG: Record<ShareKind, string> = {
  "cert": "<link rel=\"preload\" as=\"image\" href=\"/arco/02A.jpg\"/><span role=\"img\" aria-label=\"アルコちゃん：両手上げジャンプ\" style=\"display:block;width:100%;height:100%;border-radius:50%;overflow:hidden;background:#faf9f6\"><img src=\"/arco/02A.jpg\" alt=\"\" draggable=\"false\" style=\"display:block;width:100%;height:100%;object-fit:cover\"/></span>",
  "nintei": "<link rel=\"preload\" as=\"image\" href=\"/arco/02C.jpg\"/><span role=\"img\" aria-label=\"アルコちゃん：両手ほっぺ\" style=\"display:block;width:100%;height:100%;border-radius:50%;overflow:hidden;background:#faf9f6\"><img src=\"/arco/02C.jpg\" alt=\"\" draggable=\"false\" style=\"display:block;width:100%;height:100%;object-fit:cover\"/></span>",
  "medal": "<link rel=\"preload\" as=\"image\" href=\"/arco/02B.jpg\"/><span role=\"img\" aria-label=\"アルコちゃん：ダブルガッツ\" style=\"display:block;width:100%;height:100%;border-radius:50%;overflow:hidden;background:#faf9f6\"><img src=\"/arco/02B.jpg\" alt=\"\" draggable=\"false\" style=\"display:block;width:100%;height:100%;object-fit:cover\"/></span>",
  "master": "<link rel=\"preload\" as=\"image\" href=\"/arco/02A.jpg\"/><span role=\"img\" aria-label=\"アルコちゃん：両手上げジャンプ\" style=\"display:block;width:100%;height:100%;border-radius:50%;overflow:hidden;background:#faf9f6\"><img src=\"/arco/02A.jpg\" alt=\"\" draggable=\"false\" style=\"display:block;width:100%;height:100%;object-fit:cover\"/></span>",
  "rank_up": "<link rel=\"preload\" as=\"image\" href=\"/arco/02B.jpg\"/><span role=\"img\" aria-label=\"アルコちゃん：ダブルガッツ\" style=\"display:block;width:100%;height:100%;border-radius:50%;overflow:hidden;background:#faf9f6\"><img src=\"/arco/02B.jpg\" alt=\"\" draggable=\"false\" style=\"display:block;width:100%;height:100%;object-fit:cover\"/></span>",
  "weekly": "<link rel=\"preload\" as=\"image\" href=\"/arco/02C.jpg\"/><span role=\"img\" aria-label=\"アルコちゃん：両手ほっぺ\" style=\"display:block;width:100%;height:100%;border-radius:50%;overflow:hidden;background:#faf9f6\"><img src=\"/arco/02C.jpg\" alt=\"\" draggable=\"false\" style=\"display:block;width:100%;height:100%;object-fit:cover\"/></span>",
  "daily": "<link rel=\"preload\" as=\"image\" href=\"/arco/01A.jpg\"/><span role=\"img\" aria-label=\"アルコちゃん：斜め上を指す\" style=\"display:block;width:100%;height:100%;border-radius:50%;overflow:hidden;background:#faf9f6\"><img src=\"/arco/01A.jpg\" alt=\"\" draggable=\"false\" style=\"display:block;width:100%;height:100%;object-fit:cover\"/></span>"
}
