
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Plan = {
  free: 'free',
  standard: 'standard',
  premium: 'premium'
} as const

export type Plan = (typeof Plan)[keyof typeof Plan]


export const Genre = {
  pop: 'pop',
  jazz: 'jazz',
  rock: 'rock',
  classic: 'classic',
  instrumental: 'instrumental'
} as const

export type Genre = (typeof Genre)[keyof typeof Genre]


export const PerformanceType = {
  user: 'user',
  pro: 'pro'
} as const

export type PerformanceType = (typeof PerformanceType)[keyof typeof PerformanceType]


export const PerformanceStatus = {
  uploaded: 'uploaded',
  analyzed: 'analyzed',
  failed: 'failed'
} as const

export type PerformanceStatus = (typeof PerformanceStatus)[keyof typeof PerformanceStatus]


export const AnalysisStatus = {
  pending: 'pending',
  running: 'running',
  failed: 'failed'
} as const

export type AnalysisStatus = (typeof AnalysisStatus)[keyof typeof AnalysisStatus]


export const SectionType = {
  intro: 'intro',
  dev: 'dev',
  recap: 'recap'
} as const

export type SectionType = (typeof SectionType)[keyof typeof SectionType]
