
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AnalysisRun` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AnalysisRun
 * 
 */
export type AnalysisRunModel = runtime.Types.Result.DefaultSelection<Prisma.$AnalysisRunPayload>

export type AggregateAnalysisRun = {
  _count: AnalysisRunCountAggregateOutputType | null
  _avg: AnalysisRunAvgAggregateOutputType | null
  _sum: AnalysisRunSumAggregateOutputType | null
  _min: AnalysisRunMinAggregateOutputType | null
  _max: AnalysisRunMaxAggregateOutputType | null
}

export type AnalysisRunAvgAggregateOutputType = {
  confidence: number | null
}

export type AnalysisRunSumAggregateOutputType = {
  confidence: number | null
}

export type AnalysisRunMinAggregateOutputType = {
  id: string | null
  performanceId: string | null
  analysisStatus: $Enums.AnalysisStatus | null
  analysisVersion: string | null
  confidence: number | null
  startedAt: Date | null
  finishedAt: Date | null
  createdAt: Date | null
}

export type AnalysisRunMaxAggregateOutputType = {
  id: string | null
  performanceId: string | null
  analysisStatus: $Enums.AnalysisStatus | null
  analysisVersion: string | null
  confidence: number | null
  startedAt: Date | null
  finishedAt: Date | null
  createdAt: Date | null
}

export type AnalysisRunCountAggregateOutputType = {
  id: number
  performanceId: number
  analysisStatus: number
  analysisVersion: number
  confidence: number
  startedAt: number
  finishedAt: number
  resultJson: number
  createdAt: number
  _all: number
}


export type AnalysisRunAvgAggregateInputType = {
  confidence?: true
}

export type AnalysisRunSumAggregateInputType = {
  confidence?: true
}

export type AnalysisRunMinAggregateInputType = {
  id?: true
  performanceId?: true
  analysisStatus?: true
  analysisVersion?: true
  confidence?: true
  startedAt?: true
  finishedAt?: true
  createdAt?: true
}

export type AnalysisRunMaxAggregateInputType = {
  id?: true
  performanceId?: true
  analysisStatus?: true
  analysisVersion?: true
  confidence?: true
  startedAt?: true
  finishedAt?: true
  createdAt?: true
}

export type AnalysisRunCountAggregateInputType = {
  id?: true
  performanceId?: true
  analysisStatus?: true
  analysisVersion?: true
  confidence?: true
  startedAt?: true
  finishedAt?: true
  resultJson?: true
  createdAt?: true
  _all?: true
}

export type AnalysisRunAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnalysisRun to aggregate.
   */
  where?: Prisma.AnalysisRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisRuns to fetch.
   */
  orderBy?: Prisma.AnalysisRunOrderByWithRelationInput | Prisma.AnalysisRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AnalysisRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AnalysisRuns
  **/
  _count?: true | AnalysisRunCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AnalysisRunAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AnalysisRunSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AnalysisRunMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AnalysisRunMaxAggregateInputType
}

export type GetAnalysisRunAggregateType<T extends AnalysisRunAggregateArgs> = {
      [P in keyof T & keyof AggregateAnalysisRun]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAnalysisRun[P]>
    : Prisma.GetScalarType<T[P], AggregateAnalysisRun[P]>
}




export type AnalysisRunGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnalysisRunWhereInput
  orderBy?: Prisma.AnalysisRunOrderByWithAggregationInput | Prisma.AnalysisRunOrderByWithAggregationInput[]
  by: Prisma.AnalysisRunScalarFieldEnum[] | Prisma.AnalysisRunScalarFieldEnum
  having?: Prisma.AnalysisRunScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AnalysisRunCountAggregateInputType | true
  _avg?: AnalysisRunAvgAggregateInputType
  _sum?: AnalysisRunSumAggregateInputType
  _min?: AnalysisRunMinAggregateInputType
  _max?: AnalysisRunMaxAggregateInputType
}

export type AnalysisRunGroupByOutputType = {
  id: string
  performanceId: string
  analysisStatus: $Enums.AnalysisStatus
  analysisVersion: string
  confidence: number | null
  startedAt: Date
  finishedAt: Date
  resultJson: runtime.JsonValue
  createdAt: Date
  _count: AnalysisRunCountAggregateOutputType | null
  _avg: AnalysisRunAvgAggregateOutputType | null
  _sum: AnalysisRunSumAggregateOutputType | null
  _min: AnalysisRunMinAggregateOutputType | null
  _max: AnalysisRunMaxAggregateOutputType | null
}

type GetAnalysisRunGroupByPayload<T extends AnalysisRunGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AnalysisRunGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AnalysisRunGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AnalysisRunGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AnalysisRunGroupByOutputType[P]>
      }
    >
  >



export type AnalysisRunWhereInput = {
  AND?: Prisma.AnalysisRunWhereInput | Prisma.AnalysisRunWhereInput[]
  OR?: Prisma.AnalysisRunWhereInput[]
  NOT?: Prisma.AnalysisRunWhereInput | Prisma.AnalysisRunWhereInput[]
  id?: Prisma.StringFilter<"AnalysisRun"> | string
  performanceId?: Prisma.StringFilter<"AnalysisRun"> | string
  analysisStatus?: Prisma.EnumAnalysisStatusFilter<"AnalysisRun"> | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFilter<"AnalysisRun"> | string
  confidence?: Prisma.FloatNullableFilter<"AnalysisRun"> | number | null
  startedAt?: Prisma.DateTimeFilter<"AnalysisRun"> | Date | string
  finishedAt?: Prisma.DateTimeFilter<"AnalysisRun"> | Date | string
  resultJson?: Prisma.JsonFilter<"AnalysisRun">
  createdAt?: Prisma.DateTimeFilter<"AnalysisRun"> | Date | string
  performance?: Prisma.XOR<Prisma.PerformanceScalarRelationFilter, Prisma.PerformanceWhereInput>
  sections?: Prisma.SectionListRelationFilter
}

export type AnalysisRunOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  performanceId?: Prisma.SortOrder
  analysisStatus?: Prisma.SortOrder
  analysisVersion?: Prisma.SortOrder
  confidence?: Prisma.SortOrderInput | Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  resultJson?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  performance?: Prisma.PerformanceOrderByWithRelationInput
  sections?: Prisma.SectionOrderByRelationAggregateInput
}

export type AnalysisRunWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AnalysisRunWhereInput | Prisma.AnalysisRunWhereInput[]
  OR?: Prisma.AnalysisRunWhereInput[]
  NOT?: Prisma.AnalysisRunWhereInput | Prisma.AnalysisRunWhereInput[]
  performanceId?: Prisma.StringFilter<"AnalysisRun"> | string
  analysisStatus?: Prisma.EnumAnalysisStatusFilter<"AnalysisRun"> | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFilter<"AnalysisRun"> | string
  confidence?: Prisma.FloatNullableFilter<"AnalysisRun"> | number | null
  startedAt?: Prisma.DateTimeFilter<"AnalysisRun"> | Date | string
  finishedAt?: Prisma.DateTimeFilter<"AnalysisRun"> | Date | string
  resultJson?: Prisma.JsonFilter<"AnalysisRun">
  createdAt?: Prisma.DateTimeFilter<"AnalysisRun"> | Date | string
  performance?: Prisma.XOR<Prisma.PerformanceScalarRelationFilter, Prisma.PerformanceWhereInput>
  sections?: Prisma.SectionListRelationFilter
}, "id">

export type AnalysisRunOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  performanceId?: Prisma.SortOrder
  analysisStatus?: Prisma.SortOrder
  analysisVersion?: Prisma.SortOrder
  confidence?: Prisma.SortOrderInput | Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  resultJson?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AnalysisRunCountOrderByAggregateInput
  _avg?: Prisma.AnalysisRunAvgOrderByAggregateInput
  _max?: Prisma.AnalysisRunMaxOrderByAggregateInput
  _min?: Prisma.AnalysisRunMinOrderByAggregateInput
  _sum?: Prisma.AnalysisRunSumOrderByAggregateInput
}

export type AnalysisRunScalarWhereWithAggregatesInput = {
  AND?: Prisma.AnalysisRunScalarWhereWithAggregatesInput | Prisma.AnalysisRunScalarWhereWithAggregatesInput[]
  OR?: Prisma.AnalysisRunScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AnalysisRunScalarWhereWithAggregatesInput | Prisma.AnalysisRunScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AnalysisRun"> | string
  performanceId?: Prisma.StringWithAggregatesFilter<"AnalysisRun"> | string
  analysisStatus?: Prisma.EnumAnalysisStatusWithAggregatesFilter<"AnalysisRun"> | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringWithAggregatesFilter<"AnalysisRun"> | string
  confidence?: Prisma.FloatNullableWithAggregatesFilter<"AnalysisRun"> | number | null
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"AnalysisRun"> | Date | string
  finishedAt?: Prisma.DateTimeWithAggregatesFilter<"AnalysisRun"> | Date | string
  resultJson?: Prisma.JsonWithAggregatesFilter<"AnalysisRun">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AnalysisRun"> | Date | string
}

export type AnalysisRunCreateInput = {
  id?: string
  analysisStatus?: $Enums.AnalysisStatus
  analysisVersion: string
  confidence?: number | null
  startedAt: Date | string
  finishedAt: Date | string
  resultJson: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  performance: Prisma.PerformanceCreateNestedOneWithoutAnalysisRunsInput
  sections?: Prisma.SectionCreateNestedManyWithoutAnalysisRunInput
}

export type AnalysisRunUncheckedCreateInput = {
  id?: string
  performanceId: string
  analysisStatus?: $Enums.AnalysisStatus
  analysisVersion: string
  confidence?: number | null
  startedAt: Date | string
  finishedAt: Date | string
  resultJson: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  sections?: Prisma.SectionUncheckedCreateNestedManyWithoutAnalysisRunInput
}

export type AnalysisRunUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisStatus?: Prisma.EnumAnalysisStatusFieldUpdateOperationsInput | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resultJson?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  performance?: Prisma.PerformanceUpdateOneRequiredWithoutAnalysisRunsNestedInput
  sections?: Prisma.SectionUpdateManyWithoutAnalysisRunNestedInput
}

export type AnalysisRunUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceId?: Prisma.StringFieldUpdateOperationsInput | string
  analysisStatus?: Prisma.EnumAnalysisStatusFieldUpdateOperationsInput | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resultJson?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.SectionUncheckedUpdateManyWithoutAnalysisRunNestedInput
}

export type AnalysisRunCreateManyInput = {
  id?: string
  performanceId: string
  analysisStatus?: $Enums.AnalysisStatus
  analysisVersion: string
  confidence?: number | null
  startedAt: Date | string
  finishedAt: Date | string
  resultJson: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AnalysisRunUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisStatus?: Prisma.EnumAnalysisStatusFieldUpdateOperationsInput | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resultJson?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisRunUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceId?: Prisma.StringFieldUpdateOperationsInput | string
  analysisStatus?: Prisma.EnumAnalysisStatusFieldUpdateOperationsInput | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resultJson?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisRunListRelationFilter = {
  every?: Prisma.AnalysisRunWhereInput
  some?: Prisma.AnalysisRunWhereInput
  none?: Prisma.AnalysisRunWhereInput
}

export type AnalysisRunOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AnalysisRunCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  performanceId?: Prisma.SortOrder
  analysisStatus?: Prisma.SortOrder
  analysisVersion?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  resultJson?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AnalysisRunAvgOrderByAggregateInput = {
  confidence?: Prisma.SortOrder
}

export type AnalysisRunMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  performanceId?: Prisma.SortOrder
  analysisStatus?: Prisma.SortOrder
  analysisVersion?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AnalysisRunMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  performanceId?: Prisma.SortOrder
  analysisStatus?: Prisma.SortOrder
  analysisVersion?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AnalysisRunSumOrderByAggregateInput = {
  confidence?: Prisma.SortOrder
}

export type AnalysisRunScalarRelationFilter = {
  is?: Prisma.AnalysisRunWhereInput
  isNot?: Prisma.AnalysisRunWhereInput
}

export type AnalysisRunCreateNestedManyWithoutPerformanceInput = {
  create?: Prisma.XOR<Prisma.AnalysisRunCreateWithoutPerformanceInput, Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput> | Prisma.AnalysisRunCreateWithoutPerformanceInput[] | Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.AnalysisRunCreateOrConnectWithoutPerformanceInput | Prisma.AnalysisRunCreateOrConnectWithoutPerformanceInput[]
  createMany?: Prisma.AnalysisRunCreateManyPerformanceInputEnvelope
  connect?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
}

export type AnalysisRunUncheckedCreateNestedManyWithoutPerformanceInput = {
  create?: Prisma.XOR<Prisma.AnalysisRunCreateWithoutPerformanceInput, Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput> | Prisma.AnalysisRunCreateWithoutPerformanceInput[] | Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.AnalysisRunCreateOrConnectWithoutPerformanceInput | Prisma.AnalysisRunCreateOrConnectWithoutPerformanceInput[]
  createMany?: Prisma.AnalysisRunCreateManyPerformanceInputEnvelope
  connect?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
}

export type AnalysisRunUpdateManyWithoutPerformanceNestedInput = {
  create?: Prisma.XOR<Prisma.AnalysisRunCreateWithoutPerformanceInput, Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput> | Prisma.AnalysisRunCreateWithoutPerformanceInput[] | Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.AnalysisRunCreateOrConnectWithoutPerformanceInput | Prisma.AnalysisRunCreateOrConnectWithoutPerformanceInput[]
  upsert?: Prisma.AnalysisRunUpsertWithWhereUniqueWithoutPerformanceInput | Prisma.AnalysisRunUpsertWithWhereUniqueWithoutPerformanceInput[]
  createMany?: Prisma.AnalysisRunCreateManyPerformanceInputEnvelope
  set?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
  disconnect?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
  delete?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
  connect?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
  update?: Prisma.AnalysisRunUpdateWithWhereUniqueWithoutPerformanceInput | Prisma.AnalysisRunUpdateWithWhereUniqueWithoutPerformanceInput[]
  updateMany?: Prisma.AnalysisRunUpdateManyWithWhereWithoutPerformanceInput | Prisma.AnalysisRunUpdateManyWithWhereWithoutPerformanceInput[]
  deleteMany?: Prisma.AnalysisRunScalarWhereInput | Prisma.AnalysisRunScalarWhereInput[]
}

export type AnalysisRunUncheckedUpdateManyWithoutPerformanceNestedInput = {
  create?: Prisma.XOR<Prisma.AnalysisRunCreateWithoutPerformanceInput, Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput> | Prisma.AnalysisRunCreateWithoutPerformanceInput[] | Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.AnalysisRunCreateOrConnectWithoutPerformanceInput | Prisma.AnalysisRunCreateOrConnectWithoutPerformanceInput[]
  upsert?: Prisma.AnalysisRunUpsertWithWhereUniqueWithoutPerformanceInput | Prisma.AnalysisRunUpsertWithWhereUniqueWithoutPerformanceInput[]
  createMany?: Prisma.AnalysisRunCreateManyPerformanceInputEnvelope
  set?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
  disconnect?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
  delete?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
  connect?: Prisma.AnalysisRunWhereUniqueInput | Prisma.AnalysisRunWhereUniqueInput[]
  update?: Prisma.AnalysisRunUpdateWithWhereUniqueWithoutPerformanceInput | Prisma.AnalysisRunUpdateWithWhereUniqueWithoutPerformanceInput[]
  updateMany?: Prisma.AnalysisRunUpdateManyWithWhereWithoutPerformanceInput | Prisma.AnalysisRunUpdateManyWithWhereWithoutPerformanceInput[]
  deleteMany?: Prisma.AnalysisRunScalarWhereInput | Prisma.AnalysisRunScalarWhereInput[]
}

export type EnumAnalysisStatusFieldUpdateOperationsInput = {
  set?: $Enums.AnalysisStatus
}

export type AnalysisRunCreateNestedOneWithoutSectionsInput = {
  create?: Prisma.XOR<Prisma.AnalysisRunCreateWithoutSectionsInput, Prisma.AnalysisRunUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.AnalysisRunCreateOrConnectWithoutSectionsInput
  connect?: Prisma.AnalysisRunWhereUniqueInput
}

export type AnalysisRunUpdateOneRequiredWithoutSectionsNestedInput = {
  create?: Prisma.XOR<Prisma.AnalysisRunCreateWithoutSectionsInput, Prisma.AnalysisRunUncheckedCreateWithoutSectionsInput>
  connectOrCreate?: Prisma.AnalysisRunCreateOrConnectWithoutSectionsInput
  upsert?: Prisma.AnalysisRunUpsertWithoutSectionsInput
  connect?: Prisma.AnalysisRunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AnalysisRunUpdateToOneWithWhereWithoutSectionsInput, Prisma.AnalysisRunUpdateWithoutSectionsInput>, Prisma.AnalysisRunUncheckedUpdateWithoutSectionsInput>
}

export type AnalysisRunCreateWithoutPerformanceInput = {
  id?: string
  analysisStatus?: $Enums.AnalysisStatus
  analysisVersion: string
  confidence?: number | null
  startedAt: Date | string
  finishedAt: Date | string
  resultJson: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  sections?: Prisma.SectionCreateNestedManyWithoutAnalysisRunInput
}

export type AnalysisRunUncheckedCreateWithoutPerformanceInput = {
  id?: string
  analysisStatus?: $Enums.AnalysisStatus
  analysisVersion: string
  confidence?: number | null
  startedAt: Date | string
  finishedAt: Date | string
  resultJson: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  sections?: Prisma.SectionUncheckedCreateNestedManyWithoutAnalysisRunInput
}

export type AnalysisRunCreateOrConnectWithoutPerformanceInput = {
  where: Prisma.AnalysisRunWhereUniqueInput
  create: Prisma.XOR<Prisma.AnalysisRunCreateWithoutPerformanceInput, Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput>
}

export type AnalysisRunCreateManyPerformanceInputEnvelope = {
  data: Prisma.AnalysisRunCreateManyPerformanceInput | Prisma.AnalysisRunCreateManyPerformanceInput[]
}

export type AnalysisRunUpsertWithWhereUniqueWithoutPerformanceInput = {
  where: Prisma.AnalysisRunWhereUniqueInput
  update: Prisma.XOR<Prisma.AnalysisRunUpdateWithoutPerformanceInput, Prisma.AnalysisRunUncheckedUpdateWithoutPerformanceInput>
  create: Prisma.XOR<Prisma.AnalysisRunCreateWithoutPerformanceInput, Prisma.AnalysisRunUncheckedCreateWithoutPerformanceInput>
}

export type AnalysisRunUpdateWithWhereUniqueWithoutPerformanceInput = {
  where: Prisma.AnalysisRunWhereUniqueInput
  data: Prisma.XOR<Prisma.AnalysisRunUpdateWithoutPerformanceInput, Prisma.AnalysisRunUncheckedUpdateWithoutPerformanceInput>
}

export type AnalysisRunUpdateManyWithWhereWithoutPerformanceInput = {
  where: Prisma.AnalysisRunScalarWhereInput
  data: Prisma.XOR<Prisma.AnalysisRunUpdateManyMutationInput, Prisma.AnalysisRunUncheckedUpdateManyWithoutPerformanceInput>
}

export type AnalysisRunScalarWhereInput = {
  AND?: Prisma.AnalysisRunScalarWhereInput | Prisma.AnalysisRunScalarWhereInput[]
  OR?: Prisma.AnalysisRunScalarWhereInput[]
  NOT?: Prisma.AnalysisRunScalarWhereInput | Prisma.AnalysisRunScalarWhereInput[]
  id?: Prisma.StringFilter<"AnalysisRun"> | string
  performanceId?: Prisma.StringFilter<"AnalysisRun"> | string
  analysisStatus?: Prisma.EnumAnalysisStatusFilter<"AnalysisRun"> | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFilter<"AnalysisRun"> | string
  confidence?: Prisma.FloatNullableFilter<"AnalysisRun"> | number | null
  startedAt?: Prisma.DateTimeFilter<"AnalysisRun"> | Date | string
  finishedAt?: Prisma.DateTimeFilter<"AnalysisRun"> | Date | string
  resultJson?: Prisma.JsonFilter<"AnalysisRun">
  createdAt?: Prisma.DateTimeFilter<"AnalysisRun"> | Date | string
}

export type AnalysisRunCreateWithoutSectionsInput = {
  id?: string
  analysisStatus?: $Enums.AnalysisStatus
  analysisVersion: string
  confidence?: number | null
  startedAt: Date | string
  finishedAt: Date | string
  resultJson: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  performance: Prisma.PerformanceCreateNestedOneWithoutAnalysisRunsInput
}

export type AnalysisRunUncheckedCreateWithoutSectionsInput = {
  id?: string
  performanceId: string
  analysisStatus?: $Enums.AnalysisStatus
  analysisVersion: string
  confidence?: number | null
  startedAt: Date | string
  finishedAt: Date | string
  resultJson: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AnalysisRunCreateOrConnectWithoutSectionsInput = {
  where: Prisma.AnalysisRunWhereUniqueInput
  create: Prisma.XOR<Prisma.AnalysisRunCreateWithoutSectionsInput, Prisma.AnalysisRunUncheckedCreateWithoutSectionsInput>
}

export type AnalysisRunUpsertWithoutSectionsInput = {
  update: Prisma.XOR<Prisma.AnalysisRunUpdateWithoutSectionsInput, Prisma.AnalysisRunUncheckedUpdateWithoutSectionsInput>
  create: Prisma.XOR<Prisma.AnalysisRunCreateWithoutSectionsInput, Prisma.AnalysisRunUncheckedCreateWithoutSectionsInput>
  where?: Prisma.AnalysisRunWhereInput
}

export type AnalysisRunUpdateToOneWithWhereWithoutSectionsInput = {
  where?: Prisma.AnalysisRunWhereInput
  data: Prisma.XOR<Prisma.AnalysisRunUpdateWithoutSectionsInput, Prisma.AnalysisRunUncheckedUpdateWithoutSectionsInput>
}

export type AnalysisRunUpdateWithoutSectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisStatus?: Prisma.EnumAnalysisStatusFieldUpdateOperationsInput | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resultJson?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  performance?: Prisma.PerformanceUpdateOneRequiredWithoutAnalysisRunsNestedInput
}

export type AnalysisRunUncheckedUpdateWithoutSectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceId?: Prisma.StringFieldUpdateOperationsInput | string
  analysisStatus?: Prisma.EnumAnalysisStatusFieldUpdateOperationsInput | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resultJson?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisRunCreateManyPerformanceInput = {
  id?: string
  analysisStatus?: $Enums.AnalysisStatus
  analysisVersion: string
  confidence?: number | null
  startedAt: Date | string
  finishedAt: Date | string
  resultJson: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AnalysisRunUpdateWithoutPerformanceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisStatus?: Prisma.EnumAnalysisStatusFieldUpdateOperationsInput | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resultJson?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.SectionUpdateManyWithoutAnalysisRunNestedInput
}

export type AnalysisRunUncheckedUpdateWithoutPerformanceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisStatus?: Prisma.EnumAnalysisStatusFieldUpdateOperationsInput | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resultJson?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sections?: Prisma.SectionUncheckedUpdateManyWithoutAnalysisRunNestedInput
}

export type AnalysisRunUncheckedUpdateManyWithoutPerformanceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisStatus?: Prisma.EnumAnalysisStatusFieldUpdateOperationsInput | $Enums.AnalysisStatus
  analysisVersion?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resultJson?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AnalysisRunCountOutputType
 */

export type AnalysisRunCountOutputType = {
  sections: number
}

export type AnalysisRunCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sections?: boolean | AnalysisRunCountOutputTypeCountSectionsArgs
}

/**
 * AnalysisRunCountOutputType without action
 */
export type AnalysisRunCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRunCountOutputType
   */
  select?: Prisma.AnalysisRunCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AnalysisRunCountOutputType without action
 */
export type AnalysisRunCountOutputTypeCountSectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SectionWhereInput
}


export type AnalysisRunSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  performanceId?: boolean
  analysisStatus?: boolean
  analysisVersion?: boolean
  confidence?: boolean
  startedAt?: boolean
  finishedAt?: boolean
  resultJson?: boolean
  createdAt?: boolean
  performance?: boolean | Prisma.PerformanceDefaultArgs<ExtArgs>
  sections?: boolean | Prisma.AnalysisRun$sectionsArgs<ExtArgs>
  _count?: boolean | Prisma.AnalysisRunCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["analysisRun"]>

export type AnalysisRunSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  performanceId?: boolean
  analysisStatus?: boolean
  analysisVersion?: boolean
  confidence?: boolean
  startedAt?: boolean
  finishedAt?: boolean
  resultJson?: boolean
  createdAt?: boolean
  performance?: boolean | Prisma.PerformanceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["analysisRun"]>

export type AnalysisRunSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  performanceId?: boolean
  analysisStatus?: boolean
  analysisVersion?: boolean
  confidence?: boolean
  startedAt?: boolean
  finishedAt?: boolean
  resultJson?: boolean
  createdAt?: boolean
  performance?: boolean | Prisma.PerformanceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["analysisRun"]>

export type AnalysisRunSelectScalar = {
  id?: boolean
  performanceId?: boolean
  analysisStatus?: boolean
  analysisVersion?: boolean
  confidence?: boolean
  startedAt?: boolean
  finishedAt?: boolean
  resultJson?: boolean
  createdAt?: boolean
}

export type AnalysisRunOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "performanceId" | "analysisStatus" | "analysisVersion" | "confidence" | "startedAt" | "finishedAt" | "resultJson" | "createdAt", ExtArgs["result"]["analysisRun"]>
export type AnalysisRunInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  performance?: boolean | Prisma.PerformanceDefaultArgs<ExtArgs>
  sections?: boolean | Prisma.AnalysisRun$sectionsArgs<ExtArgs>
  _count?: boolean | Prisma.AnalysisRunCountOutputTypeDefaultArgs<ExtArgs>
}
export type AnalysisRunIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  performance?: boolean | Prisma.PerformanceDefaultArgs<ExtArgs>
}
export type AnalysisRunIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  performance?: boolean | Prisma.PerformanceDefaultArgs<ExtArgs>
}

export type $AnalysisRunPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AnalysisRun"
  objects: {
    performance: Prisma.$PerformancePayload<ExtArgs>
    sections: Prisma.$SectionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    performanceId: string
    analysisStatus: $Enums.AnalysisStatus
    analysisVersion: string
    confidence: number | null
    startedAt: Date
    finishedAt: Date
    resultJson: runtime.JsonValue
    createdAt: Date
  }, ExtArgs["result"]["analysisRun"]>
  composites: {}
}

export type AnalysisRunGetPayload<S extends boolean | null | undefined | AnalysisRunDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload, S>

export type AnalysisRunCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AnalysisRunFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AnalysisRunCountAggregateInputType | true
  }

export interface AnalysisRunDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AnalysisRun'], meta: { name: 'AnalysisRun' } }
  /**
   * Find zero or one AnalysisRun that matches the filter.
   * @param {AnalysisRunFindUniqueArgs} args - Arguments to find a AnalysisRun
   * @example
   * // Get one AnalysisRun
   * const analysisRun = await prisma.analysisRun.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AnalysisRunFindUniqueArgs>(args: Prisma.SelectSubset<T, AnalysisRunFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AnalysisRunClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AnalysisRun that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AnalysisRunFindUniqueOrThrowArgs} args - Arguments to find a AnalysisRun
   * @example
   * // Get one AnalysisRun
   * const analysisRun = await prisma.analysisRun.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AnalysisRunFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AnalysisRunFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnalysisRunClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnalysisRun that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRunFindFirstArgs} args - Arguments to find a AnalysisRun
   * @example
   * // Get one AnalysisRun
   * const analysisRun = await prisma.analysisRun.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AnalysisRunFindFirstArgs>(args?: Prisma.SelectSubset<T, AnalysisRunFindFirstArgs<ExtArgs>>): Prisma.Prisma__AnalysisRunClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnalysisRun that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRunFindFirstOrThrowArgs} args - Arguments to find a AnalysisRun
   * @example
   * // Get one AnalysisRun
   * const analysisRun = await prisma.analysisRun.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AnalysisRunFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AnalysisRunFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnalysisRunClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AnalysisRuns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRunFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AnalysisRuns
   * const analysisRuns = await prisma.analysisRun.findMany()
   * 
   * // Get first 10 AnalysisRuns
   * const analysisRuns = await prisma.analysisRun.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const analysisRunWithIdOnly = await prisma.analysisRun.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AnalysisRunFindManyArgs>(args?: Prisma.SelectSubset<T, AnalysisRunFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AnalysisRun.
   * @param {AnalysisRunCreateArgs} args - Arguments to create a AnalysisRun.
   * @example
   * // Create one AnalysisRun
   * const AnalysisRun = await prisma.analysisRun.create({
   *   data: {
   *     // ... data to create a AnalysisRun
   *   }
   * })
   * 
   */
  create<T extends AnalysisRunCreateArgs>(args: Prisma.SelectSubset<T, AnalysisRunCreateArgs<ExtArgs>>): Prisma.Prisma__AnalysisRunClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AnalysisRuns.
   * @param {AnalysisRunCreateManyArgs} args - Arguments to create many AnalysisRuns.
   * @example
   * // Create many AnalysisRuns
   * const analysisRun = await prisma.analysisRun.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AnalysisRunCreateManyArgs>(args?: Prisma.SelectSubset<T, AnalysisRunCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AnalysisRuns and returns the data saved in the database.
   * @param {AnalysisRunCreateManyAndReturnArgs} args - Arguments to create many AnalysisRuns.
   * @example
   * // Create many AnalysisRuns
   * const analysisRun = await prisma.analysisRun.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AnalysisRuns and only return the `id`
   * const analysisRunWithIdOnly = await prisma.analysisRun.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AnalysisRunCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AnalysisRunCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AnalysisRun.
   * @param {AnalysisRunDeleteArgs} args - Arguments to delete one AnalysisRun.
   * @example
   * // Delete one AnalysisRun
   * const AnalysisRun = await prisma.analysisRun.delete({
   *   where: {
   *     // ... filter to delete one AnalysisRun
   *   }
   * })
   * 
   */
  delete<T extends AnalysisRunDeleteArgs>(args: Prisma.SelectSubset<T, AnalysisRunDeleteArgs<ExtArgs>>): Prisma.Prisma__AnalysisRunClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AnalysisRun.
   * @param {AnalysisRunUpdateArgs} args - Arguments to update one AnalysisRun.
   * @example
   * // Update one AnalysisRun
   * const analysisRun = await prisma.analysisRun.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AnalysisRunUpdateArgs>(args: Prisma.SelectSubset<T, AnalysisRunUpdateArgs<ExtArgs>>): Prisma.Prisma__AnalysisRunClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AnalysisRuns.
   * @param {AnalysisRunDeleteManyArgs} args - Arguments to filter AnalysisRuns to delete.
   * @example
   * // Delete a few AnalysisRuns
   * const { count } = await prisma.analysisRun.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AnalysisRunDeleteManyArgs>(args?: Prisma.SelectSubset<T, AnalysisRunDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AnalysisRuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRunUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AnalysisRuns
   * const analysisRun = await prisma.analysisRun.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AnalysisRunUpdateManyArgs>(args: Prisma.SelectSubset<T, AnalysisRunUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AnalysisRuns and returns the data updated in the database.
   * @param {AnalysisRunUpdateManyAndReturnArgs} args - Arguments to update many AnalysisRuns.
   * @example
   * // Update many AnalysisRuns
   * const analysisRun = await prisma.analysisRun.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AnalysisRuns and only return the `id`
   * const analysisRunWithIdOnly = await prisma.analysisRun.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AnalysisRunUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AnalysisRunUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AnalysisRun.
   * @param {AnalysisRunUpsertArgs} args - Arguments to update or create a AnalysisRun.
   * @example
   * // Update or create a AnalysisRun
   * const analysisRun = await prisma.analysisRun.upsert({
   *   create: {
   *     // ... data to create a AnalysisRun
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AnalysisRun we want to update
   *   }
   * })
   */
  upsert<T extends AnalysisRunUpsertArgs>(args: Prisma.SelectSubset<T, AnalysisRunUpsertArgs<ExtArgs>>): Prisma.Prisma__AnalysisRunClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AnalysisRuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRunCountArgs} args - Arguments to filter AnalysisRuns to count.
   * @example
   * // Count the number of AnalysisRuns
   * const count = await prisma.analysisRun.count({
   *   where: {
   *     // ... the filter for the AnalysisRuns we want to count
   *   }
   * })
  **/
  count<T extends AnalysisRunCountArgs>(
    args?: Prisma.Subset<T, AnalysisRunCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AnalysisRunCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AnalysisRun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRunAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AnalysisRunAggregateArgs>(args: Prisma.Subset<T, AnalysisRunAggregateArgs>): Prisma.PrismaPromise<GetAnalysisRunAggregateType<T>>

  /**
   * Group by AnalysisRun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisRunGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AnalysisRunGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AnalysisRunGroupByArgs['orderBy'] }
      : { orderBy?: AnalysisRunGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AnalysisRunGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAnalysisRunGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AnalysisRun model
 */
readonly fields: AnalysisRunFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AnalysisRun.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AnalysisRunClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  performance<T extends Prisma.PerformanceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PerformanceDefaultArgs<ExtArgs>>): Prisma.Prisma__PerformanceClient<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sections<T extends Prisma.AnalysisRun$sectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AnalysisRun$sectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AnalysisRun model
 */
export interface AnalysisRunFieldRefs {
  readonly id: Prisma.FieldRef<"AnalysisRun", 'String'>
  readonly performanceId: Prisma.FieldRef<"AnalysisRun", 'String'>
  readonly analysisStatus: Prisma.FieldRef<"AnalysisRun", 'AnalysisStatus'>
  readonly analysisVersion: Prisma.FieldRef<"AnalysisRun", 'String'>
  readonly confidence: Prisma.FieldRef<"AnalysisRun", 'Float'>
  readonly startedAt: Prisma.FieldRef<"AnalysisRun", 'DateTime'>
  readonly finishedAt: Prisma.FieldRef<"AnalysisRun", 'DateTime'>
  readonly resultJson: Prisma.FieldRef<"AnalysisRun", 'Json'>
  readonly createdAt: Prisma.FieldRef<"AnalysisRun", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AnalysisRun findUnique
 */
export type AnalysisRunFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisRun to fetch.
   */
  where: Prisma.AnalysisRunWhereUniqueInput
}

/**
 * AnalysisRun findUniqueOrThrow
 */
export type AnalysisRunFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisRun to fetch.
   */
  where: Prisma.AnalysisRunWhereUniqueInput
}

/**
 * AnalysisRun findFirst
 */
export type AnalysisRunFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisRun to fetch.
   */
  where?: Prisma.AnalysisRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisRuns to fetch.
   */
  orderBy?: Prisma.AnalysisRunOrderByWithRelationInput | Prisma.AnalysisRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnalysisRuns.
   */
  cursor?: Prisma.AnalysisRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnalysisRuns.
   */
  distinct?: Prisma.AnalysisRunScalarFieldEnum | Prisma.AnalysisRunScalarFieldEnum[]
}

/**
 * AnalysisRun findFirstOrThrow
 */
export type AnalysisRunFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisRun to fetch.
   */
  where?: Prisma.AnalysisRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisRuns to fetch.
   */
  orderBy?: Prisma.AnalysisRunOrderByWithRelationInput | Prisma.AnalysisRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnalysisRuns.
   */
  cursor?: Prisma.AnalysisRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnalysisRuns.
   */
  distinct?: Prisma.AnalysisRunScalarFieldEnum | Prisma.AnalysisRunScalarFieldEnum[]
}

/**
 * AnalysisRun findMany
 */
export type AnalysisRunFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisRuns to fetch.
   */
  where?: Prisma.AnalysisRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisRuns to fetch.
   */
  orderBy?: Prisma.AnalysisRunOrderByWithRelationInput | Prisma.AnalysisRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AnalysisRuns.
   */
  cursor?: Prisma.AnalysisRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisRuns.
   */
  skip?: number
  distinct?: Prisma.AnalysisRunScalarFieldEnum | Prisma.AnalysisRunScalarFieldEnum[]
}

/**
 * AnalysisRun create
 */
export type AnalysisRunCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  /**
   * The data needed to create a AnalysisRun.
   */
  data: Prisma.XOR<Prisma.AnalysisRunCreateInput, Prisma.AnalysisRunUncheckedCreateInput>
}

/**
 * AnalysisRun createMany
 */
export type AnalysisRunCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AnalysisRuns.
   */
  data: Prisma.AnalysisRunCreateManyInput | Prisma.AnalysisRunCreateManyInput[]
}

/**
 * AnalysisRun createManyAndReturn
 */
export type AnalysisRunCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * The data used to create many AnalysisRuns.
   */
  data: Prisma.AnalysisRunCreateManyInput | Prisma.AnalysisRunCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AnalysisRun update
 */
export type AnalysisRunUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  /**
   * The data needed to update a AnalysisRun.
   */
  data: Prisma.XOR<Prisma.AnalysisRunUpdateInput, Prisma.AnalysisRunUncheckedUpdateInput>
  /**
   * Choose, which AnalysisRun to update.
   */
  where: Prisma.AnalysisRunWhereUniqueInput
}

/**
 * AnalysisRun updateMany
 */
export type AnalysisRunUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AnalysisRuns.
   */
  data: Prisma.XOR<Prisma.AnalysisRunUpdateManyMutationInput, Prisma.AnalysisRunUncheckedUpdateManyInput>
  /**
   * Filter which AnalysisRuns to update
   */
  where?: Prisma.AnalysisRunWhereInput
  /**
   * Limit how many AnalysisRuns to update.
   */
  limit?: number
}

/**
 * AnalysisRun updateManyAndReturn
 */
export type AnalysisRunUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * The data used to update AnalysisRuns.
   */
  data: Prisma.XOR<Prisma.AnalysisRunUpdateManyMutationInput, Prisma.AnalysisRunUncheckedUpdateManyInput>
  /**
   * Filter which AnalysisRuns to update
   */
  where?: Prisma.AnalysisRunWhereInput
  /**
   * Limit how many AnalysisRuns to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AnalysisRun upsert
 */
export type AnalysisRunUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  /**
   * The filter to search for the AnalysisRun to update in case it exists.
   */
  where: Prisma.AnalysisRunWhereUniqueInput
  /**
   * In case the AnalysisRun found by the `where` argument doesn't exist, create a new AnalysisRun with this data.
   */
  create: Prisma.XOR<Prisma.AnalysisRunCreateInput, Prisma.AnalysisRunUncheckedCreateInput>
  /**
   * In case the AnalysisRun was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AnalysisRunUpdateInput, Prisma.AnalysisRunUncheckedUpdateInput>
}

/**
 * AnalysisRun delete
 */
export type AnalysisRunDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  /**
   * Filter which AnalysisRun to delete.
   */
  where: Prisma.AnalysisRunWhereUniqueInput
}

/**
 * AnalysisRun deleteMany
 */
export type AnalysisRunDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnalysisRuns to delete
   */
  where?: Prisma.AnalysisRunWhereInput
  /**
   * Limit how many AnalysisRuns to delete.
   */
  limit?: number
}

/**
 * AnalysisRun.sections
 */
export type AnalysisRun$sectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Section
   */
  select?: Prisma.SectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Section
   */
  omit?: Prisma.SectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SectionInclude<ExtArgs> | null
  where?: Prisma.SectionWhereInput
  orderBy?: Prisma.SectionOrderByWithRelationInput | Prisma.SectionOrderByWithRelationInput[]
  cursor?: Prisma.SectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SectionScalarFieldEnum | Prisma.SectionScalarFieldEnum[]
}

/**
 * AnalysisRun without action
 */
export type AnalysisRunDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
}
