
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Performance` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Performance
 * 
 */
export type PerformanceModel = runtime.Types.Result.DefaultSelection<Prisma.$PerformancePayload>

export type AggregatePerformance = {
  _count: PerformanceCountAggregateOutputType | null
  _avg: PerformanceAvgAggregateOutputType | null
  _sum: PerformanceSumAggregateOutputType | null
  _min: PerformanceMinAggregateOutputType | null
  _max: PerformanceMaxAggregateOutputType | null
}

export type PerformanceAvgAggregateOutputType = {
  durationSec: number | null
}

export type PerformanceSumAggregateOutputType = {
  durationSec: number | null
}

export type PerformanceMinAggregateOutputType = {
  id: string | null
  performanceType: $Enums.PerformanceType | null
  userId: string | null
  musicId: string | null
  performanceStatus: $Enums.PerformanceStatus | null
  audioStorageKey: string | null
  durationSec: number | null
  recordedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PerformanceMaxAggregateOutputType = {
  id: string | null
  performanceType: $Enums.PerformanceType | null
  userId: string | null
  musicId: string | null
  performanceStatus: $Enums.PerformanceStatus | null
  audioStorageKey: string | null
  durationSec: number | null
  recordedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PerformanceCountAggregateOutputType = {
  id: number
  performanceType: number
  userId: number
  musicId: number
  performanceStatus: number
  audioStorageKey: number
  durationSec: number
  recordedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PerformanceAvgAggregateInputType = {
  durationSec?: true
}

export type PerformanceSumAggregateInputType = {
  durationSec?: true
}

export type PerformanceMinAggregateInputType = {
  id?: true
  performanceType?: true
  userId?: true
  musicId?: true
  performanceStatus?: true
  audioStorageKey?: true
  durationSec?: true
  recordedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type PerformanceMaxAggregateInputType = {
  id?: true
  performanceType?: true
  userId?: true
  musicId?: true
  performanceStatus?: true
  audioStorageKey?: true
  durationSec?: true
  recordedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type PerformanceCountAggregateInputType = {
  id?: true
  performanceType?: true
  userId?: true
  musicId?: true
  performanceStatus?: true
  audioStorageKey?: true
  durationSec?: true
  recordedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PerformanceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Performance to aggregate.
   */
  where?: Prisma.PerformanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Performances to fetch.
   */
  orderBy?: Prisma.PerformanceOrderByWithRelationInput | Prisma.PerformanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PerformanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Performances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Performances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Performances
  **/
  _count?: true | PerformanceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PerformanceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PerformanceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PerformanceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PerformanceMaxAggregateInputType
}

export type GetPerformanceAggregateType<T extends PerformanceAggregateArgs> = {
      [P in keyof T & keyof AggregatePerformance]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePerformance[P]>
    : Prisma.GetScalarType<T[P], AggregatePerformance[P]>
}




export type PerformanceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PerformanceWhereInput
  orderBy?: Prisma.PerformanceOrderByWithAggregationInput | Prisma.PerformanceOrderByWithAggregationInput[]
  by: Prisma.PerformanceScalarFieldEnum[] | Prisma.PerformanceScalarFieldEnum
  having?: Prisma.PerformanceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PerformanceCountAggregateInputType | true
  _avg?: PerformanceAvgAggregateInputType
  _sum?: PerformanceSumAggregateInputType
  _min?: PerformanceMinAggregateInputType
  _max?: PerformanceMaxAggregateInputType
}

export type PerformanceGroupByOutputType = {
  id: string
  performanceType: $Enums.PerformanceType
  userId: string
  musicId: string
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec: number | null
  recordedAt: Date
  createdAt: Date
  updatedAt: Date
  _count: PerformanceCountAggregateOutputType | null
  _avg: PerformanceAvgAggregateOutputType | null
  _sum: PerformanceSumAggregateOutputType | null
  _min: PerformanceMinAggregateOutputType | null
  _max: PerformanceMaxAggregateOutputType | null
}

type GetPerformanceGroupByPayload<T extends PerformanceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PerformanceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PerformanceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PerformanceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PerformanceGroupByOutputType[P]>
      }
    >
  >



export type PerformanceWhereInput = {
  AND?: Prisma.PerformanceWhereInput | Prisma.PerformanceWhereInput[]
  OR?: Prisma.PerformanceWhereInput[]
  NOT?: Prisma.PerformanceWhereInput | Prisma.PerformanceWhereInput[]
  id?: Prisma.StringFilter<"Performance"> | string
  performanceType?: Prisma.EnumPerformanceTypeFilter<"Performance"> | $Enums.PerformanceType
  userId?: Prisma.StringFilter<"Performance"> | string
  musicId?: Prisma.StringFilter<"Performance"> | string
  performanceStatus?: Prisma.EnumPerformanceStatusFilter<"Performance"> | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFilter<"Performance"> | string
  durationSec?: Prisma.FloatNullableFilter<"Performance"> | number | null
  recordedAt?: Prisma.DateTimeFilter<"Performance"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Performance"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Performance"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  music?: Prisma.XOR<Prisma.MusicScalarRelationFilter, Prisma.MusicWhereInput>
  analysisRuns?: Prisma.AnalysisRunListRelationFilter
}

export type PerformanceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  performanceType?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  musicId?: Prisma.SortOrder
  performanceStatus?: Prisma.SortOrder
  audioStorageKey?: Prisma.SortOrder
  durationSec?: Prisma.SortOrderInput | Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  music?: Prisma.MusicOrderByWithRelationInput
  analysisRuns?: Prisma.AnalysisRunOrderByRelationAggregateInput
}

export type PerformanceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PerformanceWhereInput | Prisma.PerformanceWhereInput[]
  OR?: Prisma.PerformanceWhereInput[]
  NOT?: Prisma.PerformanceWhereInput | Prisma.PerformanceWhereInput[]
  performanceType?: Prisma.EnumPerformanceTypeFilter<"Performance"> | $Enums.PerformanceType
  userId?: Prisma.StringFilter<"Performance"> | string
  musicId?: Prisma.StringFilter<"Performance"> | string
  performanceStatus?: Prisma.EnumPerformanceStatusFilter<"Performance"> | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFilter<"Performance"> | string
  durationSec?: Prisma.FloatNullableFilter<"Performance"> | number | null
  recordedAt?: Prisma.DateTimeFilter<"Performance"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Performance"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Performance"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  music?: Prisma.XOR<Prisma.MusicScalarRelationFilter, Prisma.MusicWhereInput>
  analysisRuns?: Prisma.AnalysisRunListRelationFilter
}, "id">

export type PerformanceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  performanceType?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  musicId?: Prisma.SortOrder
  performanceStatus?: Prisma.SortOrder
  audioStorageKey?: Prisma.SortOrder
  durationSec?: Prisma.SortOrderInput | Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PerformanceCountOrderByAggregateInput
  _avg?: Prisma.PerformanceAvgOrderByAggregateInput
  _max?: Prisma.PerformanceMaxOrderByAggregateInput
  _min?: Prisma.PerformanceMinOrderByAggregateInput
  _sum?: Prisma.PerformanceSumOrderByAggregateInput
}

export type PerformanceScalarWhereWithAggregatesInput = {
  AND?: Prisma.PerformanceScalarWhereWithAggregatesInput | Prisma.PerformanceScalarWhereWithAggregatesInput[]
  OR?: Prisma.PerformanceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PerformanceScalarWhereWithAggregatesInput | Prisma.PerformanceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Performance"> | string
  performanceType?: Prisma.EnumPerformanceTypeWithAggregatesFilter<"Performance"> | $Enums.PerformanceType
  userId?: Prisma.StringWithAggregatesFilter<"Performance"> | string
  musicId?: Prisma.StringWithAggregatesFilter<"Performance"> | string
  performanceStatus?: Prisma.EnumPerformanceStatusWithAggregatesFilter<"Performance"> | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringWithAggregatesFilter<"Performance"> | string
  durationSec?: Prisma.FloatNullableWithAggregatesFilter<"Performance"> | number | null
  recordedAt?: Prisma.DateTimeWithAggregatesFilter<"Performance"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Performance"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Performance"> | Date | string
}

export type PerformanceCreateInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutPerformancesInput
  music: Prisma.MusicCreateNestedOneWithoutPerformancesInput
  analysisRuns?: Prisma.AnalysisRunCreateNestedManyWithoutPerformanceInput
}

export type PerformanceUncheckedCreateInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  userId: string
  musicId: string
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  analysisRuns?: Prisma.AnalysisRunUncheckedCreateNestedManyWithoutPerformanceInput
}

export type PerformanceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutPerformancesNestedInput
  music?: Prisma.MusicUpdateOneRequiredWithoutPerformancesNestedInput
  analysisRuns?: Prisma.AnalysisRunUpdateManyWithoutPerformanceNestedInput
}

export type PerformanceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  musicId?: Prisma.StringFieldUpdateOperationsInput | string
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  analysisRuns?: Prisma.AnalysisRunUncheckedUpdateManyWithoutPerformanceNestedInput
}

export type PerformanceCreateManyInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  userId: string
  musicId: string
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PerformanceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PerformanceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  musicId?: Prisma.StringFieldUpdateOperationsInput | string
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PerformanceListRelationFilter = {
  every?: Prisma.PerformanceWhereInput
  some?: Prisma.PerformanceWhereInput
  none?: Prisma.PerformanceWhereInput
}

export type PerformanceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PerformanceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  performanceType?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  musicId?: Prisma.SortOrder
  performanceStatus?: Prisma.SortOrder
  audioStorageKey?: Prisma.SortOrder
  durationSec?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PerformanceAvgOrderByAggregateInput = {
  durationSec?: Prisma.SortOrder
}

export type PerformanceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  performanceType?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  musicId?: Prisma.SortOrder
  performanceStatus?: Prisma.SortOrder
  audioStorageKey?: Prisma.SortOrder
  durationSec?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PerformanceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  performanceType?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  musicId?: Prisma.SortOrder
  performanceStatus?: Prisma.SortOrder
  audioStorageKey?: Prisma.SortOrder
  durationSec?: Prisma.SortOrder
  recordedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PerformanceSumOrderByAggregateInput = {
  durationSec?: Prisma.SortOrder
}

export type PerformanceScalarRelationFilter = {
  is?: Prisma.PerformanceWhereInput
  isNot?: Prisma.PerformanceWhereInput
}

export type PerformanceCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutUserInput, Prisma.PerformanceUncheckedCreateWithoutUserInput> | Prisma.PerformanceCreateWithoutUserInput[] | Prisma.PerformanceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutUserInput | Prisma.PerformanceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PerformanceCreateManyUserInputEnvelope
  connect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
}

export type PerformanceUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutUserInput, Prisma.PerformanceUncheckedCreateWithoutUserInput> | Prisma.PerformanceCreateWithoutUserInput[] | Prisma.PerformanceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutUserInput | Prisma.PerformanceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PerformanceCreateManyUserInputEnvelope
  connect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
}

export type PerformanceUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutUserInput, Prisma.PerformanceUncheckedCreateWithoutUserInput> | Prisma.PerformanceCreateWithoutUserInput[] | Prisma.PerformanceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutUserInput | Prisma.PerformanceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PerformanceUpsertWithWhereUniqueWithoutUserInput | Prisma.PerformanceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PerformanceCreateManyUserInputEnvelope
  set?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  disconnect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  delete?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  connect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  update?: Prisma.PerformanceUpdateWithWhereUniqueWithoutUserInput | Prisma.PerformanceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PerformanceUpdateManyWithWhereWithoutUserInput | Prisma.PerformanceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PerformanceScalarWhereInput | Prisma.PerformanceScalarWhereInput[]
}

export type PerformanceUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutUserInput, Prisma.PerformanceUncheckedCreateWithoutUserInput> | Prisma.PerformanceCreateWithoutUserInput[] | Prisma.PerformanceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutUserInput | Prisma.PerformanceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PerformanceUpsertWithWhereUniqueWithoutUserInput | Prisma.PerformanceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PerformanceCreateManyUserInputEnvelope
  set?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  disconnect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  delete?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  connect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  update?: Prisma.PerformanceUpdateWithWhereUniqueWithoutUserInput | Prisma.PerformanceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PerformanceUpdateManyWithWhereWithoutUserInput | Prisma.PerformanceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PerformanceScalarWhereInput | Prisma.PerformanceScalarWhereInput[]
}

export type PerformanceCreateNestedManyWithoutMusicInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutMusicInput, Prisma.PerformanceUncheckedCreateWithoutMusicInput> | Prisma.PerformanceCreateWithoutMusicInput[] | Prisma.PerformanceUncheckedCreateWithoutMusicInput[]
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutMusicInput | Prisma.PerformanceCreateOrConnectWithoutMusicInput[]
  createMany?: Prisma.PerformanceCreateManyMusicInputEnvelope
  connect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
}

export type PerformanceUncheckedCreateNestedManyWithoutMusicInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutMusicInput, Prisma.PerformanceUncheckedCreateWithoutMusicInput> | Prisma.PerformanceCreateWithoutMusicInput[] | Prisma.PerformanceUncheckedCreateWithoutMusicInput[]
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutMusicInput | Prisma.PerformanceCreateOrConnectWithoutMusicInput[]
  createMany?: Prisma.PerformanceCreateManyMusicInputEnvelope
  connect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
}

export type PerformanceUpdateManyWithoutMusicNestedInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutMusicInput, Prisma.PerformanceUncheckedCreateWithoutMusicInput> | Prisma.PerformanceCreateWithoutMusicInput[] | Prisma.PerformanceUncheckedCreateWithoutMusicInput[]
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutMusicInput | Prisma.PerformanceCreateOrConnectWithoutMusicInput[]
  upsert?: Prisma.PerformanceUpsertWithWhereUniqueWithoutMusicInput | Prisma.PerformanceUpsertWithWhereUniqueWithoutMusicInput[]
  createMany?: Prisma.PerformanceCreateManyMusicInputEnvelope
  set?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  disconnect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  delete?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  connect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  update?: Prisma.PerformanceUpdateWithWhereUniqueWithoutMusicInput | Prisma.PerformanceUpdateWithWhereUniqueWithoutMusicInput[]
  updateMany?: Prisma.PerformanceUpdateManyWithWhereWithoutMusicInput | Prisma.PerformanceUpdateManyWithWhereWithoutMusicInput[]
  deleteMany?: Prisma.PerformanceScalarWhereInput | Prisma.PerformanceScalarWhereInput[]
}

export type PerformanceUncheckedUpdateManyWithoutMusicNestedInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutMusicInput, Prisma.PerformanceUncheckedCreateWithoutMusicInput> | Prisma.PerformanceCreateWithoutMusicInput[] | Prisma.PerformanceUncheckedCreateWithoutMusicInput[]
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutMusicInput | Prisma.PerformanceCreateOrConnectWithoutMusicInput[]
  upsert?: Prisma.PerformanceUpsertWithWhereUniqueWithoutMusicInput | Prisma.PerformanceUpsertWithWhereUniqueWithoutMusicInput[]
  createMany?: Prisma.PerformanceCreateManyMusicInputEnvelope
  set?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  disconnect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  delete?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  connect?: Prisma.PerformanceWhereUniqueInput | Prisma.PerformanceWhereUniqueInput[]
  update?: Prisma.PerformanceUpdateWithWhereUniqueWithoutMusicInput | Prisma.PerformanceUpdateWithWhereUniqueWithoutMusicInput[]
  updateMany?: Prisma.PerformanceUpdateManyWithWhereWithoutMusicInput | Prisma.PerformanceUpdateManyWithWhereWithoutMusicInput[]
  deleteMany?: Prisma.PerformanceScalarWhereInput | Prisma.PerformanceScalarWhereInput[]
}

export type EnumPerformanceTypeFieldUpdateOperationsInput = {
  set?: $Enums.PerformanceType
}

export type EnumPerformanceStatusFieldUpdateOperationsInput = {
  set?: $Enums.PerformanceStatus
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PerformanceCreateNestedOneWithoutAnalysisRunsInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutAnalysisRunsInput, Prisma.PerformanceUncheckedCreateWithoutAnalysisRunsInput>
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutAnalysisRunsInput
  connect?: Prisma.PerformanceWhereUniqueInput
}

export type PerformanceUpdateOneRequiredWithoutAnalysisRunsNestedInput = {
  create?: Prisma.XOR<Prisma.PerformanceCreateWithoutAnalysisRunsInput, Prisma.PerformanceUncheckedCreateWithoutAnalysisRunsInput>
  connectOrCreate?: Prisma.PerformanceCreateOrConnectWithoutAnalysisRunsInput
  upsert?: Prisma.PerformanceUpsertWithoutAnalysisRunsInput
  connect?: Prisma.PerformanceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PerformanceUpdateToOneWithWhereWithoutAnalysisRunsInput, Prisma.PerformanceUpdateWithoutAnalysisRunsInput>, Prisma.PerformanceUncheckedUpdateWithoutAnalysisRunsInput>
}

export type PerformanceCreateWithoutUserInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  music: Prisma.MusicCreateNestedOneWithoutPerformancesInput
  analysisRuns?: Prisma.AnalysisRunCreateNestedManyWithoutPerformanceInput
}

export type PerformanceUncheckedCreateWithoutUserInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  musicId: string
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  analysisRuns?: Prisma.AnalysisRunUncheckedCreateNestedManyWithoutPerformanceInput
}

export type PerformanceCreateOrConnectWithoutUserInput = {
  where: Prisma.PerformanceWhereUniqueInput
  create: Prisma.XOR<Prisma.PerformanceCreateWithoutUserInput, Prisma.PerformanceUncheckedCreateWithoutUserInput>
}

export type PerformanceCreateManyUserInputEnvelope = {
  data: Prisma.PerformanceCreateManyUserInput | Prisma.PerformanceCreateManyUserInput[]
}

export type PerformanceUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PerformanceWhereUniqueInput
  update: Prisma.XOR<Prisma.PerformanceUpdateWithoutUserInput, Prisma.PerformanceUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PerformanceCreateWithoutUserInput, Prisma.PerformanceUncheckedCreateWithoutUserInput>
}

export type PerformanceUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PerformanceWhereUniqueInput
  data: Prisma.XOR<Prisma.PerformanceUpdateWithoutUserInput, Prisma.PerformanceUncheckedUpdateWithoutUserInput>
}

export type PerformanceUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PerformanceScalarWhereInput
  data: Prisma.XOR<Prisma.PerformanceUpdateManyMutationInput, Prisma.PerformanceUncheckedUpdateManyWithoutUserInput>
}

export type PerformanceScalarWhereInput = {
  AND?: Prisma.PerformanceScalarWhereInput | Prisma.PerformanceScalarWhereInput[]
  OR?: Prisma.PerformanceScalarWhereInput[]
  NOT?: Prisma.PerformanceScalarWhereInput | Prisma.PerformanceScalarWhereInput[]
  id?: Prisma.StringFilter<"Performance"> | string
  performanceType?: Prisma.EnumPerformanceTypeFilter<"Performance"> | $Enums.PerformanceType
  userId?: Prisma.StringFilter<"Performance"> | string
  musicId?: Prisma.StringFilter<"Performance"> | string
  performanceStatus?: Prisma.EnumPerformanceStatusFilter<"Performance"> | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFilter<"Performance"> | string
  durationSec?: Prisma.FloatNullableFilter<"Performance"> | number | null
  recordedAt?: Prisma.DateTimeFilter<"Performance"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Performance"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Performance"> | Date | string
}

export type PerformanceCreateWithoutMusicInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutPerformancesInput
  analysisRuns?: Prisma.AnalysisRunCreateNestedManyWithoutPerformanceInput
}

export type PerformanceUncheckedCreateWithoutMusicInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  userId: string
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  analysisRuns?: Prisma.AnalysisRunUncheckedCreateNestedManyWithoutPerformanceInput
}

export type PerformanceCreateOrConnectWithoutMusicInput = {
  where: Prisma.PerformanceWhereUniqueInput
  create: Prisma.XOR<Prisma.PerformanceCreateWithoutMusicInput, Prisma.PerformanceUncheckedCreateWithoutMusicInput>
}

export type PerformanceCreateManyMusicInputEnvelope = {
  data: Prisma.PerformanceCreateManyMusicInput | Prisma.PerformanceCreateManyMusicInput[]
}

export type PerformanceUpsertWithWhereUniqueWithoutMusicInput = {
  where: Prisma.PerformanceWhereUniqueInput
  update: Prisma.XOR<Prisma.PerformanceUpdateWithoutMusicInput, Prisma.PerformanceUncheckedUpdateWithoutMusicInput>
  create: Prisma.XOR<Prisma.PerformanceCreateWithoutMusicInput, Prisma.PerformanceUncheckedCreateWithoutMusicInput>
}

export type PerformanceUpdateWithWhereUniqueWithoutMusicInput = {
  where: Prisma.PerformanceWhereUniqueInput
  data: Prisma.XOR<Prisma.PerformanceUpdateWithoutMusicInput, Prisma.PerformanceUncheckedUpdateWithoutMusicInput>
}

export type PerformanceUpdateManyWithWhereWithoutMusicInput = {
  where: Prisma.PerformanceScalarWhereInput
  data: Prisma.XOR<Prisma.PerformanceUpdateManyMutationInput, Prisma.PerformanceUncheckedUpdateManyWithoutMusicInput>
}

export type PerformanceCreateWithoutAnalysisRunsInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutPerformancesInput
  music: Prisma.MusicCreateNestedOneWithoutPerformancesInput
}

export type PerformanceUncheckedCreateWithoutAnalysisRunsInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  userId: string
  musicId: string
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PerformanceCreateOrConnectWithoutAnalysisRunsInput = {
  where: Prisma.PerformanceWhereUniqueInput
  create: Prisma.XOR<Prisma.PerformanceCreateWithoutAnalysisRunsInput, Prisma.PerformanceUncheckedCreateWithoutAnalysisRunsInput>
}

export type PerformanceUpsertWithoutAnalysisRunsInput = {
  update: Prisma.XOR<Prisma.PerformanceUpdateWithoutAnalysisRunsInput, Prisma.PerformanceUncheckedUpdateWithoutAnalysisRunsInput>
  create: Prisma.XOR<Prisma.PerformanceCreateWithoutAnalysisRunsInput, Prisma.PerformanceUncheckedCreateWithoutAnalysisRunsInput>
  where?: Prisma.PerformanceWhereInput
}

export type PerformanceUpdateToOneWithWhereWithoutAnalysisRunsInput = {
  where?: Prisma.PerformanceWhereInput
  data: Prisma.XOR<Prisma.PerformanceUpdateWithoutAnalysisRunsInput, Prisma.PerformanceUncheckedUpdateWithoutAnalysisRunsInput>
}

export type PerformanceUpdateWithoutAnalysisRunsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutPerformancesNestedInput
  music?: Prisma.MusicUpdateOneRequiredWithoutPerformancesNestedInput
}

export type PerformanceUncheckedUpdateWithoutAnalysisRunsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  musicId?: Prisma.StringFieldUpdateOperationsInput | string
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PerformanceCreateManyUserInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  musicId: string
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PerformanceUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  music?: Prisma.MusicUpdateOneRequiredWithoutPerformancesNestedInput
  analysisRuns?: Prisma.AnalysisRunUpdateManyWithoutPerformanceNestedInput
}

export type PerformanceUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  musicId?: Prisma.StringFieldUpdateOperationsInput | string
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  analysisRuns?: Prisma.AnalysisRunUncheckedUpdateManyWithoutPerformanceNestedInput
}

export type PerformanceUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  musicId?: Prisma.StringFieldUpdateOperationsInput | string
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PerformanceCreateManyMusicInput = {
  id?: string
  performanceType: $Enums.PerformanceType
  userId: string
  performanceStatus: $Enums.PerformanceStatus
  audioStorageKey: string
  durationSec?: number | null
  recordedAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PerformanceUpdateWithoutMusicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutPerformancesNestedInput
  analysisRuns?: Prisma.AnalysisRunUpdateManyWithoutPerformanceNestedInput
}

export type PerformanceUncheckedUpdateWithoutMusicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  analysisRuns?: Prisma.AnalysisRunUncheckedUpdateManyWithoutPerformanceNestedInput
}

export type PerformanceUncheckedUpdateManyWithoutMusicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  performanceType?: Prisma.EnumPerformanceTypeFieldUpdateOperationsInput | $Enums.PerformanceType
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  performanceStatus?: Prisma.EnumPerformanceStatusFieldUpdateOperationsInput | $Enums.PerformanceStatus
  audioStorageKey?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  recordedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PerformanceCountOutputType
 */

export type PerformanceCountOutputType = {
  analysisRuns: number
}

export type PerformanceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  analysisRuns?: boolean | PerformanceCountOutputTypeCountAnalysisRunsArgs
}

/**
 * PerformanceCountOutputType without action
 */
export type PerformanceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PerformanceCountOutputType
   */
  select?: Prisma.PerformanceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PerformanceCountOutputType without action
 */
export type PerformanceCountOutputTypeCountAnalysisRunsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnalysisRunWhereInput
}


export type PerformanceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  performanceType?: boolean
  userId?: boolean
  musicId?: boolean
  performanceStatus?: boolean
  audioStorageKey?: boolean
  durationSec?: boolean
  recordedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.Performance$userArgs<ExtArgs>
  music?: boolean | Prisma.MusicDefaultArgs<ExtArgs>
  analysisRuns?: boolean | Prisma.Performance$analysisRunsArgs<ExtArgs>
  _count?: boolean | Prisma.PerformanceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["performance"]>

export type PerformanceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  performanceType?: boolean
  userId?: boolean
  musicId?: boolean
  performanceStatus?: boolean
  audioStorageKey?: boolean
  durationSec?: boolean
  recordedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.Performance$userArgs<ExtArgs>
  music?: boolean | Prisma.MusicDefaultArgs<ExtArgs>
}, ExtArgs["result"]["performance"]>

export type PerformanceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  performanceType?: boolean
  userId?: boolean
  musicId?: boolean
  performanceStatus?: boolean
  audioStorageKey?: boolean
  durationSec?: boolean
  recordedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.Performance$userArgs<ExtArgs>
  music?: boolean | Prisma.MusicDefaultArgs<ExtArgs>
}, ExtArgs["result"]["performance"]>

export type PerformanceSelectScalar = {
  id?: boolean
  performanceType?: boolean
  userId?: boolean
  musicId?: boolean
  performanceStatus?: boolean
  audioStorageKey?: boolean
  durationSec?: boolean
  recordedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PerformanceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "performanceType" | "userId" | "musicId" | "performanceStatus" | "audioStorageKey" | "durationSec" | "recordedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["performance"]>
export type PerformanceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Performance$userArgs<ExtArgs>
  music?: boolean | Prisma.MusicDefaultArgs<ExtArgs>
  analysisRuns?: boolean | Prisma.Performance$analysisRunsArgs<ExtArgs>
  _count?: boolean | Prisma.PerformanceCountOutputTypeDefaultArgs<ExtArgs>
}
export type PerformanceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Performance$userArgs<ExtArgs>
  music?: boolean | Prisma.MusicDefaultArgs<ExtArgs>
}
export type PerformanceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Performance$userArgs<ExtArgs>
  music?: boolean | Prisma.MusicDefaultArgs<ExtArgs>
}

export type $PerformancePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Performance"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
    music: Prisma.$MusicPayload<ExtArgs>
    analysisRuns: Prisma.$AnalysisRunPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    performanceType: $Enums.PerformanceType
    userId: string
    musicId: string
    performanceStatus: $Enums.PerformanceStatus
    audioStorageKey: string
    durationSec: number | null
    recordedAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["performance"]>
  composites: {}
}

export type PerformanceGetPayload<S extends boolean | null | undefined | PerformanceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PerformancePayload, S>

export type PerformanceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PerformanceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PerformanceCountAggregateInputType | true
  }

export interface PerformanceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Performance'], meta: { name: 'Performance' } }
  /**
   * Find zero or one Performance that matches the filter.
   * @param {PerformanceFindUniqueArgs} args - Arguments to find a Performance
   * @example
   * // Get one Performance
   * const performance = await prisma.performance.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PerformanceFindUniqueArgs>(args: Prisma.SelectSubset<T, PerformanceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PerformanceClient<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Performance that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PerformanceFindUniqueOrThrowArgs} args - Arguments to find a Performance
   * @example
   * // Get one Performance
   * const performance = await prisma.performance.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PerformanceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PerformanceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PerformanceClient<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Performance that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PerformanceFindFirstArgs} args - Arguments to find a Performance
   * @example
   * // Get one Performance
   * const performance = await prisma.performance.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PerformanceFindFirstArgs>(args?: Prisma.SelectSubset<T, PerformanceFindFirstArgs<ExtArgs>>): Prisma.Prisma__PerformanceClient<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Performance that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PerformanceFindFirstOrThrowArgs} args - Arguments to find a Performance
   * @example
   * // Get one Performance
   * const performance = await prisma.performance.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PerformanceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PerformanceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PerformanceClient<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Performances that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PerformanceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Performances
   * const performances = await prisma.performance.findMany()
   * 
   * // Get first 10 Performances
   * const performances = await prisma.performance.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const performanceWithIdOnly = await prisma.performance.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PerformanceFindManyArgs>(args?: Prisma.SelectSubset<T, PerformanceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Performance.
   * @param {PerformanceCreateArgs} args - Arguments to create a Performance.
   * @example
   * // Create one Performance
   * const Performance = await prisma.performance.create({
   *   data: {
   *     // ... data to create a Performance
   *   }
   * })
   * 
   */
  create<T extends PerformanceCreateArgs>(args: Prisma.SelectSubset<T, PerformanceCreateArgs<ExtArgs>>): Prisma.Prisma__PerformanceClient<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Performances.
   * @param {PerformanceCreateManyArgs} args - Arguments to create many Performances.
   * @example
   * // Create many Performances
   * const performance = await prisma.performance.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PerformanceCreateManyArgs>(args?: Prisma.SelectSubset<T, PerformanceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Performances and returns the data saved in the database.
   * @param {PerformanceCreateManyAndReturnArgs} args - Arguments to create many Performances.
   * @example
   * // Create many Performances
   * const performance = await prisma.performance.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Performances and only return the `id`
   * const performanceWithIdOnly = await prisma.performance.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PerformanceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PerformanceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Performance.
   * @param {PerformanceDeleteArgs} args - Arguments to delete one Performance.
   * @example
   * // Delete one Performance
   * const Performance = await prisma.performance.delete({
   *   where: {
   *     // ... filter to delete one Performance
   *   }
   * })
   * 
   */
  delete<T extends PerformanceDeleteArgs>(args: Prisma.SelectSubset<T, PerformanceDeleteArgs<ExtArgs>>): Prisma.Prisma__PerformanceClient<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Performance.
   * @param {PerformanceUpdateArgs} args - Arguments to update one Performance.
   * @example
   * // Update one Performance
   * const performance = await prisma.performance.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PerformanceUpdateArgs>(args: Prisma.SelectSubset<T, PerformanceUpdateArgs<ExtArgs>>): Prisma.Prisma__PerformanceClient<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Performances.
   * @param {PerformanceDeleteManyArgs} args - Arguments to filter Performances to delete.
   * @example
   * // Delete a few Performances
   * const { count } = await prisma.performance.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PerformanceDeleteManyArgs>(args?: Prisma.SelectSubset<T, PerformanceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Performances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PerformanceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Performances
   * const performance = await prisma.performance.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PerformanceUpdateManyArgs>(args: Prisma.SelectSubset<T, PerformanceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Performances and returns the data updated in the database.
   * @param {PerformanceUpdateManyAndReturnArgs} args - Arguments to update many Performances.
   * @example
   * // Update many Performances
   * const performance = await prisma.performance.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Performances and only return the `id`
   * const performanceWithIdOnly = await prisma.performance.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PerformanceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PerformanceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Performance.
   * @param {PerformanceUpsertArgs} args - Arguments to update or create a Performance.
   * @example
   * // Update or create a Performance
   * const performance = await prisma.performance.upsert({
   *   create: {
   *     // ... data to create a Performance
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Performance we want to update
   *   }
   * })
   */
  upsert<T extends PerformanceUpsertArgs>(args: Prisma.SelectSubset<T, PerformanceUpsertArgs<ExtArgs>>): Prisma.Prisma__PerformanceClient<runtime.Types.Result.GetResult<Prisma.$PerformancePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Performances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PerformanceCountArgs} args - Arguments to filter Performances to count.
   * @example
   * // Count the number of Performances
   * const count = await prisma.performance.count({
   *   where: {
   *     // ... the filter for the Performances we want to count
   *   }
   * })
  **/
  count<T extends PerformanceCountArgs>(
    args?: Prisma.Subset<T, PerformanceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PerformanceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Performance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PerformanceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PerformanceAggregateArgs>(args: Prisma.Subset<T, PerformanceAggregateArgs>): Prisma.PrismaPromise<GetPerformanceAggregateType<T>>

  /**
   * Group by Performance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PerformanceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PerformanceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PerformanceGroupByArgs['orderBy'] }
      : { orderBy?: PerformanceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PerformanceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPerformanceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Performance model
 */
readonly fields: PerformanceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Performance.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PerformanceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.Performance$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Performance$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  music<T extends Prisma.MusicDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MusicDefaultArgs<ExtArgs>>): Prisma.Prisma__MusicClient<runtime.Types.Result.GetResult<Prisma.$MusicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  analysisRuns<T extends Prisma.Performance$analysisRunsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Performance$analysisRunsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisRunPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Performance model
 */
export interface PerformanceFieldRefs {
  readonly id: Prisma.FieldRef<"Performance", 'String'>
  readonly performanceType: Prisma.FieldRef<"Performance", 'PerformanceType'>
  readonly userId: Prisma.FieldRef<"Performance", 'String'>
  readonly musicId: Prisma.FieldRef<"Performance", 'String'>
  readonly performanceStatus: Prisma.FieldRef<"Performance", 'PerformanceStatus'>
  readonly audioStorageKey: Prisma.FieldRef<"Performance", 'String'>
  readonly durationSec: Prisma.FieldRef<"Performance", 'Float'>
  readonly recordedAt: Prisma.FieldRef<"Performance", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Performance", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Performance", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Performance findUnique
 */
export type PerformanceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
  /**
   * Filter, which Performance to fetch.
   */
  where: Prisma.PerformanceWhereUniqueInput
}

/**
 * Performance findUniqueOrThrow
 */
export type PerformanceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
  /**
   * Filter, which Performance to fetch.
   */
  where: Prisma.PerformanceWhereUniqueInput
}

/**
 * Performance findFirst
 */
export type PerformanceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
  /**
   * Filter, which Performance to fetch.
   */
  where?: Prisma.PerformanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Performances to fetch.
   */
  orderBy?: Prisma.PerformanceOrderByWithRelationInput | Prisma.PerformanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Performances.
   */
  cursor?: Prisma.PerformanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Performances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Performances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Performances.
   */
  distinct?: Prisma.PerformanceScalarFieldEnum | Prisma.PerformanceScalarFieldEnum[]
}

/**
 * Performance findFirstOrThrow
 */
export type PerformanceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
  /**
   * Filter, which Performance to fetch.
   */
  where?: Prisma.PerformanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Performances to fetch.
   */
  orderBy?: Prisma.PerformanceOrderByWithRelationInput | Prisma.PerformanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Performances.
   */
  cursor?: Prisma.PerformanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Performances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Performances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Performances.
   */
  distinct?: Prisma.PerformanceScalarFieldEnum | Prisma.PerformanceScalarFieldEnum[]
}

/**
 * Performance findMany
 */
export type PerformanceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
  /**
   * Filter, which Performances to fetch.
   */
  where?: Prisma.PerformanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Performances to fetch.
   */
  orderBy?: Prisma.PerformanceOrderByWithRelationInput | Prisma.PerformanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Performances.
   */
  cursor?: Prisma.PerformanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Performances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Performances.
   */
  skip?: number
  distinct?: Prisma.PerformanceScalarFieldEnum | Prisma.PerformanceScalarFieldEnum[]
}

/**
 * Performance create
 */
export type PerformanceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
  /**
   * The data needed to create a Performance.
   */
  data: Prisma.XOR<Prisma.PerformanceCreateInput, Prisma.PerformanceUncheckedCreateInput>
}

/**
 * Performance createMany
 */
export type PerformanceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Performances.
   */
  data: Prisma.PerformanceCreateManyInput | Prisma.PerformanceCreateManyInput[]
}

/**
 * Performance createManyAndReturn
 */
export type PerformanceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * The data used to create many Performances.
   */
  data: Prisma.PerformanceCreateManyInput | Prisma.PerformanceCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Performance update
 */
export type PerformanceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
  /**
   * The data needed to update a Performance.
   */
  data: Prisma.XOR<Prisma.PerformanceUpdateInput, Prisma.PerformanceUncheckedUpdateInput>
  /**
   * Choose, which Performance to update.
   */
  where: Prisma.PerformanceWhereUniqueInput
}

/**
 * Performance updateMany
 */
export type PerformanceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Performances.
   */
  data: Prisma.XOR<Prisma.PerformanceUpdateManyMutationInput, Prisma.PerformanceUncheckedUpdateManyInput>
  /**
   * Filter which Performances to update
   */
  where?: Prisma.PerformanceWhereInput
  /**
   * Limit how many Performances to update.
   */
  limit?: number
}

/**
 * Performance updateManyAndReturn
 */
export type PerformanceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * The data used to update Performances.
   */
  data: Prisma.XOR<Prisma.PerformanceUpdateManyMutationInput, Prisma.PerformanceUncheckedUpdateManyInput>
  /**
   * Filter which Performances to update
   */
  where?: Prisma.PerformanceWhereInput
  /**
   * Limit how many Performances to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Performance upsert
 */
export type PerformanceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
  /**
   * The filter to search for the Performance to update in case it exists.
   */
  where: Prisma.PerformanceWhereUniqueInput
  /**
   * In case the Performance found by the `where` argument doesn't exist, create a new Performance with this data.
   */
  create: Prisma.XOR<Prisma.PerformanceCreateInput, Prisma.PerformanceUncheckedCreateInput>
  /**
   * In case the Performance was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PerformanceUpdateInput, Prisma.PerformanceUncheckedUpdateInput>
}

/**
 * Performance delete
 */
export type PerformanceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
  /**
   * Filter which Performance to delete.
   */
  where: Prisma.PerformanceWhereUniqueInput
}

/**
 * Performance deleteMany
 */
export type PerformanceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Performances to delete
   */
  where?: Prisma.PerformanceWhereInput
  /**
   * Limit how many Performances to delete.
   */
  limit?: number
}

/**
 * Performance.user
 */
export type Performance$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Performance.analysisRuns
 */
export type Performance$analysisRunsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisRun
   */
  select?: Prisma.AnalysisRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisRun
   */
  omit?: Prisma.AnalysisRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisRunInclude<ExtArgs> | null
  where?: Prisma.AnalysisRunWhereInput
  orderBy?: Prisma.AnalysisRunOrderByWithRelationInput | Prisma.AnalysisRunOrderByWithRelationInput[]
  cursor?: Prisma.AnalysisRunWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AnalysisRunScalarFieldEnum | Prisma.AnalysisRunScalarFieldEnum[]
}

/**
 * Performance without action
 */
export type PerformanceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Performance
   */
  select?: Prisma.PerformanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Performance
   */
  omit?: Prisma.PerformanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PerformanceInclude<ExtArgs> | null
}
